server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wcjb

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 300 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头
